stages:
  - build
  - lint
  - test

default:
  image: node:18.17.1

.standard-rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  CACHE_DIR: '$CI_PROJECT_DIR/node_modules'
  TEST_REPORTS_DIR: '$CI_PROJECT_DIR/test-reports'
  COVERAGE_DIR: '$CI_PROJECT_DIR/coverage'

cache:
  key: '${CI_COMMIT_REF_SLUG}'
  paths:
    - '$CACHE_DIR'

build-source-dev:
  stage: build
  script:
    - node --version
    - yarn install
    - yarn build
  artifacts:
    paths:
      - 'build/'

linting:
  stage: lint
  script:
    - npm run lint

testing:
  stage: test
  script:
    - npm test -- --coverage --coverageDirectory=$COVERAGE_DIR
  coverage: '/^Statements\s*:\s*100%\s*$/'
  artifacts:
    paths:
      - '$COVERAGE_DIR/'
