stages:
  - build
  - test

default:
  image: node

.standard-rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  NODE_VERSION: '18.17.1'
  CACHE_DIR: '$CI_PROJECT_DIR/node_modules'
  TEST_REPORTS_DIR: '$CI_PROJECT_DIR/test-reports'
  COVERAGE_DIR: '$CI_PROJECT_DIR/coverage'

cache:
  key: '${CI_COMMIT_REF_SLUG}'
  paths:
    - '$CACHE_DIR'

build-source-dev:
  stage: build
  script:
    - node --version
    - yarn install
    - yarn build
  artifacts:
    paths:
      - 'build/'

unit_test:
  stage: test
  script:
    - yarn test:cov'
  # coverage: '/Code coverage: \d+(?:\.\d+)?/'
