name: CI pipeline

run-name: Build CI by ${{ github.actor }}

on:
  push:
    branches:
      - 'develop'
      - 'release'
      - 'main'
  pull_request:
    branches:
      - 'develop'
      - 'release'
      - 'main'
      - 'base/*'

jobs:
  build:
    name: Build & Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com

      - name: Cache node modules
        id: cache-yarn
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        if: steps.cache-yarn.outputs.cache-hit != 'true'
        run: |
          echo ${{steps.cache-yarn.outputs.cache-hit}}     
          yarn install

      - name: Build-source-code
        run: yarn build

      - name: Testing
        if: ${{ always() }}
        run: yarn test:cov

      - name: Linting
        id: execute-lint
        if: ${{ always() }}
        run: yarn lint
