name: CI pipeline

run-name: Build CI by ${{ github.actor }}

on:
  push:
    branches:
      - 'develop'
      - 'release'
      - 'main'
  pull_request:
    branches:
      - 'develop'
      - 'release'
      - 'main'
      - 'base/*'

jobs:
  build:
    name: Build & Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Linting
        run: yarn lint

      - name: Testing
        run: yarn test:cov
